site_name: Cartografìa de rutas del autobùses
site_author: Sören Reinecke alias Valor Naram
repo_url: https://github.com/trufi-association/mapping-documentation-spanish
repo_name: mapping-documentation-spanish
site_description: Documentation in Spanish for communities along the Trufi Association stream who need to map bus routes for OpenStreetMap.

theme: readthedocs

markdown_extensions:
 - admonition
